# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to='myApp/pictures'),
        ),
    ]
